query GetHospitals($page: Int, $size: Int) {
  hospitals(page: $page, size: $size) {
    hospitals {
      id
      name
      address
      dailyRate
    }
    pageInfo {
      totalElements
      totalPages
      currentPage
    }
  }
}

query GetHospital($id: ID!) {
  hospital(id: $id) {
    id
    name
    address
    dailyRate
  }
}

query GetHospitalsByPatient($patientId: ID!, $page: Int, $size: Int) {
  hospitalsByPatient(patientId: $patientId, page: $page, size: $size) {
    hospitals {
      id
      name
      address
      dailyRate
    }
    pageInfo {
      totalElements
      totalPages
      currentPage
    }
  }
}

mutation CreateHospital($name: String!, $address: String!, $dailyRate: Int!) {
  createHospital(name: $name, address: $address, dailyRate: $dailyRate) {
    id
    name
    address
    dailyRate
  }
}

mutation UpdateHospital($id: ID!, $name: String, $address: String, $dailyRate: Int) {
  updateHospital(id: $id, name: $name, address: $address, dailyRate: $dailyRate) {
    id
    name
    address
    dailyRate
  }
}

mutation DeleteHospital($id: ID!) {
  deleteHospital(id: $id)
}
